import { PortfolioData } from '@/types';

export const portfolioData: PortfolioData = {
  name: "Ibrahim Ilias Ouazzani",
  tagline: "AI Systems Builder | Content Creator | Community Contributor",
  summary:
    "A versatile creator spanning AI development, video content, and event volunteering. Experienced in configuring distributed AI systems, building NLP-powered chatbots, growing audiences to 27K+ followers, and volunteering at major international events. Equally comfortable deploying OpenClaw on Linux, editing football compilations, or coordinating at a stadium.",
  contact: {
    email: "iliasouazzani303@gmail.com",
    phone: "+212 615153736",
  },
  languages: [
    { name: "Arabic", level: "Native" },
    { name: "French", level: "Intermediate" },
    { name: "English", level: "Fluent" },
  ],
  links: [
    {
      platform: "GitHub",
      url: "https://github.com/iliasouazzani/Internship_ecommerce_website",
      icon: "FaGithub",
    },
    {
      platform: "TikTok",
      url: "https://www.tiktok.com/@panamixbra7",
      icon: "FaTiktok",
    },
  ],
  experiences: [
    {
      id: "ai-internship",
      title: "AI Systems Intern",
      subtitle: "E-Commerce & AI Agent Development",
      period: "1 Month",
      type: "internship",
      description: [
        "Configured and set up an AI agent called \"OpenClaw\" on a Linux operating system (Ubuntu 24.04).",
        "Linked 3 separate PCs together, all running Linux, to distribute the computational/processing load between them (distributed computing).",
        "Integrated a Large Language Model (LLM) into the OpenClaw AI agent.",
        "Connected the OpenClaw AI agent to Telegram, enabling remote control of machines from a distance using only Telegram on a phone.",
        "Built a website for selling electronics (tablets, phones, headsets, PlayStations) as part of the internship.",
        "The website was \"vibe-coded\" (built quickly with heavy AI assistance) using React, PHP, Symfony, JavaScript, and Docker.",
        "Personal hands-on contribution: coding the website's chatbot, built with NLP and a set of predefined questions/answers.",
        "The website has an admin account/dashboard showing all products and their order status: Sold, In Shipping, Shipped, and Pending. This admin system runs via the OpenClaw AI agent, which distributes the computational load across all 3 linked Linux machines.",
      ],
      tags: [
        "Linux",
        "OpenClaw",
        "LLM Integration",
        "Distributed Computing",
        "Telegram Bot",
        "React",
        "PHP",
        "Symfony",
        "Docker",
        "NLP",
      ],
    },
    {
      id: "hackathon-child-guard",
      title: "Child Guard Project",
      subtitle: "Hedera Hashgraph Hackathon",
      period: "Event",
      type: "hackathon",
      description: [
        "Helped deliver the project's live demonstration.",
        "Coded the website for the project.",
        "Project purpose: Child Guard lets people declare a child missing the instant it happens, instead of the usual requirement of waiting 24 hours before a child can be officially declared missing.",
        "Created a video edit used as the demonstration during the project's presentation.",
        "Personally coded a chatbot assistant for the project using NLP, written in Python.",
      ],
      tags: ["Python", "NLP", "Chatbot", "Video Editing", "Web Development"],
    },
    {
      id: "freelance-content",
      title: "Freelance Video Editor & Content Manager",
      subtitle: "TikTok (@panamixbra7)",
      period: "4 Months",
      type: "freelance",
      description: [
        "Grew the account to 27,000 followers in just 4 months.",
        "Reached over 20 million views during those same 4 months.",
        "Content type: editing motivational videos and football edits.",
      ],
      tags: [
        "Video Editing",
        "Content Strategy",
        "TikTok Growth",
        "Football Edits",
        "Motivational Content",
      ],
    },
    {
      id: "volunteering-stadium",
      title: "Event Operations Volunteer",
      subtitle: "Prince Moulay Abdellah Stadium, Rabat, Morocco",
      period: "Multiple Events",
      type: "volunteering",
      description: [
        "African Cup of Nations (Men's Edition), 2025",
        "CAF Champions League Final, 2025/2026",
        "Morocco vs. Madagascar friendly match, 2026",
        "Mawazine Festival concerts, June 2026 edition",
      ],
      tags: [
        "Event Coordination",
        "Crowd Management",
        "Hospitality",
        "Teamwork",
      ],
    },
  ],
  education: [
    {
      degree: "Diploma in Artificial Intelligence, specialized in Chatbot Development",
      period: "2024–2026",
    },
    {
      degree: "Baccalaureate in Physical Sciences",
      period: "2024",
    },
  ],
  skills: [
    { name: "Linux (Ubuntu) System Configuration", category: "technical" },
    { name: "AI Agent Setup & Configuration (OpenClaw)", category: "technical" },
    { name: "LLM Integration", category: "technical" },
    { name: "Telegram Bot Integration", category: "technical" },
    { name: "Distributed Computing", category: "technical" },
    { name: "NLP-Based Chatbot Development", category: "technical" },
    { name: "Python", category: "technical" },
    { name: "React", category: "technical" },
    { name: "PHP / Symfony", category: "technical" },
    { name: "JavaScript", category: "technical" },
    { name: "Docker", category: "technical" },
    { name: "Video Editing", category: "technical" },
    { name: "TypeScript", category: "technical" },
    { name: "Next.js", category: "technical" },
    { name: "Tailwind CSS", category: "technical" },
    { name: "Framer Motion", category: "technical" },
    { name: "Three.js / WebGL", category: "technical" },
    { name: "Git & GitHub", category: "technical" },
    { name: "REST APIs", category: "technical" },
    { name: "Handles Stress Well", category: "soft" },
    { name: "Fast and Accurate", category: "soft" },
    { name: "Active Listener", category: "soft" },
    { name: "Asks Questions When Something Is Unclear", category: "soft" },
    { name: "Understanding", category: "soft" },
    { name: "Adaptable Team Player", category: "soft" },
  ],
  volunteering: [
    {
      id: "afcon-2025",
      event: "African Cup of Nations (Men's Edition)",
      location: "Prince Moulay Abdellah Stadium, Rabat",
      date: "2025",
    },
    {
      id: "caf-final-2025",
      event: "CAF Champions League Final",
      location: "Prince Moulay Abdellah Stadium, Rabat",
      date: "2025/2026",
    },
    {
      id: "morocco-mada-2026",
      event: "Morocco vs. Madagascar Friendly Match",
      location: "Prince Moulay Abdellah Stadium, Rabat",
      date: "2026",
    },
    {
      id: "mawazine-2026",
      event: "Mawazine Festival Concerts",
      location: "Prince Moulay Abdellah Stadium, Rabat",
      date: "June 2026",
    },
  ],
  contentStats: {
    followers: 27000,
    views: 20000000,
    platform: "TikTok",
    handle: "@panamixbra7",
    growthPeriod: "4 months",
  },
};
